name: Check CRN

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 08:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DROPBOX_ALL_ACCESS_REFRESH_TOKEN: ${{ secrets.DROPBOX_ALL_ACCESS_REFRESH_TOKEN }}
      DROPBOX_ALL_ACCESS_APP_KEY: ${{ secrets.DROPBOX_ALL_ACCESS_APP_KEY }}
      DROPBOX_ALL_ACCESS_APP_SECRET: ${{ secrets.DROPBOX_ALL_ACCESS_APP_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl requests

      - name: Run script
        run: python Others/mergeQs.py

      - name: Upload merged file to Dropbox
        uses: ./upload-dropbox-action
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_ALL_ACCESS_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_ALL_ACCESS_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_ALL_ACCESS_REFRESH_TOKEN }}
          SOURCE_PATH: Others/Merged Cin7 Sales.xlsx
          DEST_PATH: /Power BI Data Warehouse/Source of truth/2025/Merged Cin7 Sales.xlsx


      